### ISSUE TITLE
Consider: don't use host bind mounts at all

### ISSUE THREAD

**Issue by jbeda** [thockin/go-build-template#1]
Using host bind mounts only works well when you are on Linux.  Docker for Mac is super slow.  It also means that your local workstation has to be your local build machine.

We should explore how much more complicated it is to not user local bind mounts and explicitly transfer input/output to container.

The experience with Kubernetes suggests it isn't worth it for smaller projects but we should look regardless.

Related: http://docker-sync.io/

**Comment by thockin** [comment]
Yeah.  Part of the motivation for this repo was to prove that all the bullshit in the Kubernetes build (I say that with mad respect, Joe :) is because MacOS is crap.  I think Kubernetes should abandon native mac build support, or should relegate all the complexity to a mac-specific file that the rest of us don't have to touch.

**Comment by thockin** [comment]
But PRs welcome if we can solve it without resorting to data containers and rsync.
