### ISSUE TITLE
Blog Post - Makefile you need!

### ISSUE THREAD

**Issue by alok87** [thockin/go-build-template#77]
I am writing a blog post to convince others to use go-build-template and have a Makefile like this repo. I have used this for a long time now and like its Makefile very much. Thank you.

### Few screenshots on blog - WIP
<img width="1019" alt="Screenshot 2022-12-12 at 10 07 56 AM" src="https://user-images.githubusercontent.com/9006763/206961850-5b1202bc-2daa-4a83-b52d-4b55cfe50efd.png">

<img width="1033" alt="Screenshot 2022-12-12 at 10 14 28 AM" src="https://user-images.githubusercontent.com/9006763/206962503-05071236-9883-4d8e-b0ed-f5d147df15a6.png">

### Few things I am considering
- All tasks are behind container - Consistent experience and no deps to install locally, clone, and start using. Everything is there in the build image.
- CI works the same
- Make gives the consistent API across repos for the build, test, etc...
- Image caching? Since we miss out on docker multi-stage builds, does the caching of images a concern with the template `Dockerfile.in` the approach
- Single Dockerfile for all deployable in a repo - I see many repos maintain tons of Dockerifle for diff environments - like dev ones need extra things installed, etc...
- Parameterized Generic Makefile

@thockin please suggest some top pointers and considerations as content that you think should be there in that post and I may be missing out.

**Comment by alok87** [comment]
What is the universal approach then? Curious to know how others do it. The containerized part is a definitely a need but if not Make orchestrating that then what?

I still see make everywhere, this repos make brings some standard to do it and we can have similar make for each stack.

**Comment by thockin** [comment]
`make` is as close as we get to universal, which is why I ran with it, but I don't know ANYONE who joined our industry in the last 10 years who knows how it really works, and even among people who DO know how to write a Makefile only know 10-15% of the feature set.  This makes it hard to really get creative.

This project uses `make` for a few of the common things that need specific flags, but it could just as easily be a set of shell scripts.  And because of the way `make` commandline works, there isn't a good enquivalent for `go test ./pkg/foo ./pkg/bar`, so it's an incomplete abstraction at best.

Don't get me wrong, I am not saying don't advocate!  There isn't a better answer (sadly).  Do what works for you.

**Comment by alok87** [comment]
@thockin have u looked at https://github.com/magefile/mage?
